FROM node:11.15

LABEL version="1.0"
LABEL Description="node12.3.1 npm6.9.0"
LABEL maintainer="bruce<heyuan110@gmail.com>" 
LABEL dockerhub="https://hub.docker.com/u/heyuan110"
LABEL github="https://github.com/heyuan110/docker-app"

# add gulp 
RUN npm install --global gulp