FROM nginx:1.15.12-alpine

LABEL version="1.0"
LABEL Description="nginx1.15.12"
LABEL maintainer="bruce<heyuan110@gmail.com>" 
LABEL dockerhub="https://hub.docker.com/u/heyuan110"
LABEL github="https://github.com/heyuan110/docker-app"


