FROM php:7.2-fpm

LABEL version="1.0"
LABEL description="PHP FPM pp_cus_7.2.18"
LABEL editdate="2021/03/09 15:00:00 GTM+8"
LABEL maintainer="bruce.he<bruce.he@patpat.com>" 
LABEL dockerhub="AWS ECR"

#redis version
ENV  REDIS_VERSION=4.0.1

#install php extensions, -j$(nproc)表示调用CPU可用的核进行并行编译，可以加快便已速度。
RUN apt-get update \
    && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libpng-dev \
    # 增加 mongodb 扩展
    && pecl install mongodb \
    && docker-php-ext-enable mongodb \
    # 打开xdebug
    && pecl install xdebug-2.9.6 \
    && docker-php-ext-enable xdebug \   
    # gd扩展
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    # gettext bcmath pdo_mysql 扩展
    && docker-php-ext-install -j$(nproc) bcmath gettext pdo_mysql \
    # redis 扩展
    && pecl install redis-${REDIS_VERSION} \
    && docker-php-ext-enable redis \
    # 增加 mcrypt 扩展 
    && apt-get install -y --no-install-recommends libmcrypt-dev \
    && pecl install mcrypt-1.0.1 \
    && docker-php-ext-enable mcrypt \
    # 增加 zip 扩展
    && apt-get install -y --no-install-recommends libzip-dev\
    && docker-php-ext-install -j$(nproc) zip \
    # 清理文件
    && pecl clear-cache \
    && apt-get clean \
    && rm -r /var/lib/apt/lists/* \
    && rm -rf /tmp/*